---
apiVersion: v1
kind: Secret
metadata:
  name: wt-wind-turbine-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/keynote-demo/wt-wind-turbine-gitops
